version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/
hooks:
 BeforeInstall:
    - location: webpack.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: npm-start.sh
      timeout: 60
      runas: ec2-user
