const autoComplete = {
  ProvinceState: {
    canada: [
      'AB - Alberta',
      'BC - British Columbia',
      'MB - Manitoba',
      'NB - New Brunswick',
      'NL - Newfoundland and Labrador',
      'NT - Northwest Territories',
      'NS - Nova Scotia',
      'NU - Nunavut',
      'ON - Ontario',
      'PE - Prince Edward Island',
      'QC - Quebec',
      'SK - Saskatchewan',
      'YT -Yukon Territory'
    ],
    us: [
      "AL - Alabama",
      "AR - Arkansas",
      "AK - Alaska",
      "AZ - Arizona",
      "AS - American Samoa",
      "CA - California",
      "CO - Colorado",
      "CT - Connecticut",
      "DC - District of Columbia",
      "DE - Delaware",
      "FL - Florida",
      "GA - Georgia",
      "GU - Guam",
      "HI - Hawaii",
      "IA - Iowa",
      "ID - Idaho",
      "IL - Illinois",
      "IN - Indiana",
      "KS - Kansas",
      "KY - Kentucky",
      "LA - Louisiana",
      "MA - Massachusetts",
      "MD - Maryland",
      "ME - Maine",
      "MI - Michigan",
      "MN - Minnesota",
      "MO - Missouri",
      "MS - Mississippi",
      "MT - Montana",
      "NC - North Carolina",
      "ND - North Dakota",
      "NE - Nebraska",
      "NH - New Hampshire",
      "NJ - New Jersey",
      "NM - New Mexico",
      "NV - Nevada",
      "NY - New York",
      "OH - Ohio",
      "OK - Oklahoma",
      "OR - Oregon",
      "PA - Pennsylvania",
      "PR - Puerto Rico",
      "RI - Rhode Island",
      "SC - South Carolina",
      "SD - South Dakota",
      "TN - Tennessee",
      "TX - Texas",
      "UT - Utah",
      "VA - Virginia",
      "VI - Virgin Islands",
      "VT - Vermont",
      "WA - Washington",
      "WI - Wisconsin",
      "WV - West Virginia",
      "WY - Wyoming"
    ]
  },
  credentials: {
    certType : [
      "RCC", "CCC", "RPsych", "LMFT", "Psychiatrist","RSW","MFT","LMFT"
    ],
    certBody : [
      "BCACC","CCPA","OACPP"
    ],
    service: [
      "Adults",
      "Children",
      "Couples",
      "Elders",
      "Youth",
      "Adolescents",
      "Families",
      "Communities",
      "Veterans"
    ],
    issues : [
      "Anxiety",
      "Depression",
      "Grief/Loss",
      "Trauma",
      "Abuse",
      "Addictions",
      "Eating Disorders",
      "Substance misuse",
      "Mental Health Diagnosis",
      "Stress",
      "Chronic Pain",
      "Insomnia and sleep issues",
      "Anger management",
      "Work-life balance",
      "Life transitions",
      "Career counselling",
      "Personal Growth",
      "Self-esteem",
      "Body image difficulties",
      "Spirituality",
      "Parenting",
      "Family conflict",
      "Relationships",
      "Infidelity",
      "Divorce",
      "Separation",
      "Reunification",
      "Sexuality",
      "Gender Identity exploration and concerns",
      "Sexual orientation exploration and concerns",
      "Motor Vehicle Accident",
      "Crime Victims Assistance",
      "ADD / ADHD",
      "Obsessive compulsive behaviors",
      "Bipolar disorders",
      "Personality disorders",
      "Learning disabilities",
      "PTSD"
    ],
    modalities: [
      "Person-centred",
      "Existential",
      "Psychodynamic",
      "Jungian",
      "Attachment",
      "Gestalt",
      "Emotionally-Focused Therapy",
      "Narrative Therapy",
      "Solution-focused therapy",
      "Feminist therapy",
      "Collaborative therapy",
      "Somatic Experiencing",
      "Interpersonal neurobiology",
      "EMDR",
      "Hakomi",
      "Mindfulness-based",
      "CBT",
      "ACT",
      "DBT",
      "Focusing",
      "Culturally-informed",
      "Response-based practice",
      "Expressive arts therapies",
      "Relational-cultural",
      "Integrative Body Psychotherapy",
      "Eclectic"
    ]
  },
  languages : [
    "English",
    "French",
    "Chinese",
    "Italian",
    "Punjabi",
    "Portuguese",
    "Cree",
    "Inuktitut",
    "Athabaskan",
    "German",
    "Tagalog",
    "Ukrainian",
    "Spanish",
    "Arabic",
    "Urdu"
  ]

}
export default autoComplete